### ISSUE TITLE
openapi 3.0 yaml does not correctly honor responses specified without single quotes 

### ISSUE THREAD

**Issue by generatz** [schemathesis/schemathesis#829] opened 2020-10-22 12:37 UTC
With CLI, this spec works in an openapi 3.0 yaml file:
```
      responses:
        '200':
```
but this:
```
      responses:
        200:
```
results in:
An internal error happened during a test run
Error: jsonschema.exceptions.ValidationError: Invalid schema

Ubuntu 18.04
schemathesiss 2.70
python 3.6.9

**Comment by Stranger6667** [comment] 2020-10-22 13:02
Hi @generatz !

This is intended behavior since schemas with status codes as numbers are invalid.

See more info in [this issue](https://github.com/schemathesis/schemathesis/issues/610)

We can try to catch it and provide a more helpful message though. I think it could be done relatively easy + improve docs on this matter.

**Comment by generatz** [comment] 2020-11-03 21:04
I was misinformed and had thought that numbers were valid. Thanks for straightening me out!

**Comment by Stranger6667** [comment] 2020-11-03 21:23
You are very welcome! I'll keep the issue open until a more detailed error is added to Schemathesis :)

**Comment by Stranger6667** [comment] 2020-12-25 17:21
Closing in favor of #834

**Closed by Stranger6667** 2020-12-25 17:21 UTC
Labels: Difficulty: Medium, Priority: High, Type: Enhancement
