### ISSUE TITLE
[BUG] - Error running with more than 1 worker and some hyphothesis

### ISSUE THREAD

**Issue by lucasmayoni** [schemathesis/schemathesis#860] opened 2020-11-12 19:27 UTC
**Describe the bug**
Running the commando within certain params, Im getting a error (like an exception) but all test cases are passing. The problem is running with 2 or more workers and with more than 27 hypothesis examples. 

**To Reproduce**
1. Command
schemathesis run --stateful=links --stateful-recursion-limit=3 --checks=all --workers=2 --hypothesis-deadline=None --hypothesis-suppress-health-check=too_slow,filter_too_much --validate-schema=true --show-errors-tracebacks --hypothesis-max-examples=27 http://localhost:8100/v1/openapi.json
2. Error given
```
======================================================================================= Schemathesis test session starts ======================================================================================
platform Linux -- Python 3.7.9, schemathesis-2.7.5, hypothesis-5.41.1, hypothesis_jsonschema-0.18.0, jsonschema-3.2.0
rootdir: /home/lm/code/project
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/lm/code/project/.hypothesis/examples')
Schema location: http://localhost:8100/v1/openapi.json
Base URL: http://localhost:8100/v1
Specification version: Open API 3.0.0
Workers: 2
collected endpoints: 6

...E.........

==================================================================================================== ERRORS ===================================================================================================
_________________________________________________________________________________ PUT: /v1/asset_credentials/{credentials_id} _________________________________________________________________________________
Traceback (most recent call last):
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/schemathesis/runner/impl/core.py", line 115, in run_test
    test(checks, targets, result, headers=headers, **kwargs)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/schemathesis/runner/impl/core.py", line 230, in network_test
    case: Case,
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 1162, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 1131, in wrapped_test
    state.run_engine()
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 750, in run_engine
    runner.run()
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/engine.py", line 497, in run
    self._run()
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/engine.py", line 899, in _run
    self.generate_new_examples()
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/engine.py", line 750, in generate_new_examples
    self.test_function(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/engine.py", line 218, in test_function
    self.__stoppable_test_function(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/engine.py", line 194, in __stoppable_test_function
    self._test_function(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 703, in _execute_once_for_engine
    escalate_hypothesis_internal_error()
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 674, in _execute_once_for_engine
    result = self.execute_once(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 629, in execute_once
    result = self.test_runner(data, run)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/executors.py", line 52, in default_new_style_executor
    return function(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 569, in run
    args, kwargs = data.draw(self.search_strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 887, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/core.py", line 218, in do_draw
    return self.mapped_strategy.do_draw(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 650, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/lazy.py", line 150, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 650, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/lazy.py", line 150, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 650, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/lazy.py", line 150, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 650, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/collections.py", line 57, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/core.py", line 1809, in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis_jsonschema/_from_schema.py", line 585, in from_object_schema
    out[key] = draw(merged_as_strategies(pattern_schemas, custom_formats))
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 724, in do_draw
    data=data, filter_strategy=self
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 352, in do_filtered_draw
    return filter_strategy.default_do_filtered_draw(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 739, in default_do_filtered_draw
    value = data.draw(self.filtered_strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 589, in do_draw
    return data.draw(strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 724, in do_draw
    data=data, filter_strategy=self
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/lazy.py", line 154, in do_filtered_draw
    data=data, filter_strategy=filter_strategy
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 352, in do_filtered_draw
    return filter_strategy.default_do_filtered_draw(data)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/strategies.py", line 739, in default_do_filtered_draw
    value = data.draw(self.filtered_strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/lazy.py", line 150, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/core.py", line 1809, in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis_jsonschema/_from_schema.py", line 587, in from_object_schema
    out[key] = draw(from_schema(additional, custom_formats=custom_formats))
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/internal/conjecture/data.py", line 883, in draw
    return strategy.do_draw(self)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/recursive.py", line 98, in do_draw
    with self.limited_base.capped(self.max_leaves):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/hypothesis/strategies/_internal/recursive.py", line 50, in capped
    assert not self.currently_capped
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lm/.virtualenvs/project/lib/python3.7/site-packages/schemathesis/runner/impl/core.py", line 170, in reraise
    raise InvalidSchema(message) from error
schemathesis.exceptions.InvalidSchema: Unknown schema error

=================================================================================================== SUMMARY ===================================================================================================

Performed checks:
    not_a_server_error                              220 / 220 passed          PASSED 
    status_code_conformance                         220 / 220 passed          PASSED 
    content_type_conformance                        220 / 220 passed          PASSED 
    response_headers_conformance                    220 / 220 passed          PASSED 
    response_schema_conformance                     220 / 220 passed          PASSED 

```
If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
{
    "openapi": "3.0.0"
    put:
      summary: Updates credentials with id credentials_id.
      tags:
        - a c
      operationId: ac.api.update
      requestBody:
        required: true
        content:
          application/json:
            schema:
             $ref: "#/components/schemas/CredentialsWithPass"
      responses:
        '202':
          description: Updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metadata"
          links:
            GetCredentialById:
              $ref: '#/components/links/GetCredentialById'
            GetCredentialWPassById:
              $ref: '#/components/links/GetCredentialWPassById'
            DeleteCredentialsById:
              $ref: '#/components/links/DeleteCredentialsById'
            UpdateCredentialsById:
              $ref: '#/components/links/UpdateCredentialsById'
        '400':
          description: Invalid provided body credentials or id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          $ref: '#/components/responses/404InvalidCredentialsId'
        '503':
          $ref: '#/components/responses/503ConnectionKV'
}
```

**Expected behavior**
The idea is that to use more than 2 workers and at most 100 examples. This is to cover most of the API Cases

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04LTS
 - Python version: 3.7.9
 - Schemathesis version: 2.7.5
 - Spec version: OpenAPI 3.0.0

**Comment by Stranger6667** [comment] 2020-11-13 18:30
Hi @lucasmayoni !

Could you, please provide the resolved version of the schema? I assume that "#/components/schemas/CredentialsWithPass" has recursive references inside, but can't confirm it without the resolved version. Currently, such references are capped, but there could be some corner cases where it doesn't work. The complete solution could be implemented in Schemathesis once https://github.com/Zac-HD/hypothesis-jsonschema/pull/61 is finalized and merged, however, I am not sure when I'll get back to it.

Also, as you mention running Schemathesis with multiple workers - do you have the same error when running tests with a single worker?

**Comment by Stranger6667** [comment] 2020-11-13 18:32
Also, thank you for reporting this! Having Schemathesis run stable on any valid schemas is important for us :)

**Comment by lucasmayoni** [comment] 2020-11-13 18:45
Hi! No, when run only with 1 worker, I have no error at all. Its all green jaja. The problem is with multiple workers. The reference is
`CredentialsWithPass:
      type: object
      properties:
        connection_params:
            $ref: '#/components/schemas/Connection_params'
        credentials:
            $ref: '#/components/schemas/Credentials_field_with_pass'
      required:
        - credentials
        - connection_params`

And then "Connection_params" and "Credentials_field_with_pass" are same as 
`type: object
      properties:
        app:
          type: object
          properties:
            instance_number:
              type: string
              pattern: "[0-9]{2}"
          required:
            - instance_number
          additionalProperties: false`

**Comment by Stranger6667** [comment] 2020-11-13 19:53
Thanks! I will take a look at this issue in the next few days

**Comment by Stranger6667** [comment] 2020-12-05 13:14
Sorry for not getting back to you! I have a couple of things to finish, and when they are done, I'll get back to this issue

**Comment by Stranger6667** [comment] 2020-12-25 18:46
The problem is that underneath there is a shared strategy that is accessed by multiple threads, and a race condition occurs. I [reported](https://github.com/HypothesisWorks/hypothesis/issues/2717) it to Hypothesis, and once it is resolved, I will bump the Hypothesis version here, release a new version with these changes and close this issue :) Likely it will be a part of the Schemathesis 3.0 release

**Comment by lucasmayoni** [comment] 2020-12-28 12:48
Great! I'll stay tuned. Thanks!

**Comment by Stranger6667** [comment] 2021-03-11 18:51
Schemathesis `3.2.2` supports Hypothesis 6, where the issue is fixed. Let me know if it doesn't work for your use case.

**Closed by Stranger6667** 2021-03-11 18:51 UTC
Labels: Difficulty: Medium, Priority: Medium, Status: Need More Info, Type: Bug
