### ISSUE TITLE
[BUG] Docker image can't connect to localhost

### ISSUE THREAD

**Issue by GvandeSteeg** [schemathesis/schemathesis#1157] opened 2021-05-10 10:43 UTC
**Describe the bug**
According to the [Pypi docs](https://pypi.org/project/schemathesis/1.2.0/), we should be able to run the schemathesis Docker image vs a localhost api. When I use schemathesis from the command line everything works as expected, but when using `kiwicom/schemathesis:stable` even with `--networks="host"` it refuses to connect.

**To Reproduce**
Run the api code as described in the README [here](https://github.com/python-restx/flask-restx)

```
docker run --network="host" kiwicom/schemathesis:stable run http://localhost:5000/swagger.json
Failed to load schema from http://localhost:5000/swagger.json
Error: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d77eeb50>: Failed to establish a new connection: [Errno 111] Connection refused'))

Add this option to your command line parameters to see full tracebacks: --show-errors-tracebacks
```
Full traceback is linked [here](https://pastebin.com/g8EXrpCh)

If possible, please post a minimal version of your API schema that cause this behavior:
n/a

**Expected behavior**
Docker container connects to localhost and executes Schemathesis tests

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Python version: 3.8.2
 - Schemathesis version: stable
 - Spec version: Open API 3.0.2

**Comment by Stranger6667** [comment] 2021-05-10 10:53
Hi @GvandeSteeg !

You referenced an outdated Schemathesis version (1.2) - new images are pushed to `schemathesis/schemathesis` rather than `kiwicom/schemathesis`. As per the stable [docs](https://schemathesis.readthedocs.io/en/stable/cli.html#running-cli-via-docker).

Could you, please, try again with the most recent Schemathesis version?

**Comment by GvandeSteeg** [comment] 2021-05-10 12:41
Hi @Stranger6667 !

I've tried again with `schemathesis/schemathesis`, but the problem remains the same:

```
docker run --network="host" schemathesis/schemathesis:stable run http://localhost:5000/swagger.json --show-errors-tracebacks
Unable to find image 'schemathesis/schemathesis:stable' locally
stable: Pulling from schemathesis/schemathesis
f782feae6139: Pull complete
ec2f6d359f5f: Pull complete
6c99cec23dcd: Pull complete
dc8825ff6229: Pull complete
9acbb9a970f7: Pull complete
d037238c5194: Pull complete
d449ac8a15f8: Pull complete
10d876e39fda: Pull complete
2c3cf7022de1: Pull complete
ad0357e07526: Pull complete
Digest: sha256:abab5978fc866922f71239bb33b3d76e5b792488f69a811baaac474da57f8480
Status: Downloaded newer image for schemathesis/schemathesis:stable
Failed to load schema from http://localhost:5000/swagger.json
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa70d718220>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa70d718220>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/schemathesis/cli/__init__.py", line 605, in into_event_stream
    loaded_schema = load_schema(
  File "/usr/local/lib/python3.9/site-packages/schemathesis/cli/__init__.py", line 684, in load_schema
    return loader(schema_location, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/schemathesis/specs/openapi/loaders.py", line 87, in from_uri
    response = requests.get(uri, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa70d718220>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by Stranger6667** [comment] 2021-05-10 12:47
I assume that it is caused by the app config & the used URL:
- Try to set `host="0.0.0.0"` in the `app.run` call
- Use `0.0.0.0:5000` instead of `localhost` in the docker command

Let me know if the above helps - At the moment, I don't have much time to check it myself (I probably will have it later this week).

**Comment by GvandeSteeg** [comment] 2021-05-10 12:58
Could you explain the `app.run` bit please? I've tried `--app` but that doesn't accept `"host=0.0.0.0"` and when I try to give it my module path `--app=".schemathesis-test:app"` it throws a ModuleNotFoundError

**Comment by Stranger6667** [comment] 2021-05-10 13:02
Sure!

As you mentioned the example app from flask-restx, I think that the following change on the last line can solve the issue:

```python
if __name__ == '__main__':
    app.run(host="0.0.0.0", debug=True)
```

**Comment by GvandeSteeg** [comment] 2021-05-10 13:45
```
tail -n 1 schemathesis-test/api.py
    app.run(host="0.0.0.0", debug=True)

docker run --network="host" schemathesis/schemathesis:stable run http://0.0.0.0:5000/swagger.json
Failed to load schema from http://0.0.0.0:5000/swagger.json
Error: requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=5000): Max retries exceeded with url: /swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8ea723d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by Stranger6667** [comment] 2021-05-10 14:44
Thanks! I'll take a deeper look in the next few days

**Comment by GvandeSteeg** [comment] 2021-05-10 20:05
Just to confirm it's only occurring with the Docker image for me:

```
schemathesis run http://localhost:5000/swagger.json
=================================================== Schemathesis test session starts ==================================================
platform Darwin -- Python 3.8.2, schemathesis-3.6.3, hypothesis-6.10.1, hypothesis_jsonschema-0.19.1, jsonschema-3.2.0
rootdir: /Users/gv4/PycharmProjects/scrap
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/gv4/PycharmProjects/scrap/.hypothesis/examples')
Schema location: http://localhost:5000/swagger.json
Base URL: http://localhost:5000/
Specification version: Swagger 2.0
Workers: 1
Collected API operations: 5

POST /todos/ .                                                                                                                   [ 20%]
GET /todos/ .                                                                                                                    [ 40%]
PUT /todos/{id} .                                                                                                                [ 60%]
DELETE /todos/{id} .                                                                                                             [ 80%]
GET /todos/{id} .                                                                                                                [100%]

=============================================================== SUMMARY ===============================================================

Performed checks:
    not_a_server_error                    500 / 500 passed          PASSED

========================================================== 5 passed in 9.82s ==========================================================
(base)

docker run --network="host" schemathesis/schemathesis:stable run http://localhost:5000/swagger.json
Failed to load schema from http://localhost:5000/swagger.json
Error: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4337fb490>: Failed to establish a new connection: [Errno 111] Connection refused'))

Add this option to your command line parameters to see full tracebacks: --show-errors-tracebacks
(base)
```

**Comment by hnataraj** [comment] 2021-05-10 20:30
All my tests were using the stable docker image.

Perhaps you have some firewall/NAT rules in your setup that is blocking
connectivity.

Here is how I would diagnose it:
1. Build a linux image which has ping, curl, wget, ifconfig, telnet,
traceroute, SSH, and SSH server
2. Launch the image with --network="host" and attach to it
3. telnet to localhost 5000

If step 3 fails, you have a networking problem and not related to
Schemathesis.

If step 3 pases, try:
4. WGET http://localhost:5000

If step 4 passes, we will need to attach to the container that has
Schemathesis and repeat the steps 1,2,3 to diagnose it further.

Hope this helps ...

Best regards,

Harish
Cell: 425-443-0526

**Comment by GvandeSteeg** [comment] 2021-05-11 10:54
Ah yes, step 3 is failing. I thought it might be my work VPN, but even with that turned off it still doesn't work.. I'll reach out to our IT teams, thanks!

**Comment by Stranger6667** [comment] 2021-05-14 09:59
@hnataraj Thank you for helping out!

As it doesn't seem to be related to Schemathesis, I close this issue :) @GvandeSteeg let me know if there are any further problems that we can help with from the Schemathesis side

**Closed by Stranger6667** 2021-05-14 09:59 UTC
Labels: Type: Bug
