### ISSUE TITLE
[BUG] Incompatible regexp formats forcing validation to be disabled

### ISSUE THREAD

**Issue by DavidFarago** [schemathesis/schemathesis#1241] opened 2021-08-15 15:50 UTC
**Describe the bug**
Schemathesis and my middleware `express-openapi-validator` interpret regular expressions differently, forcing me to disable `express-openapi-validator`'s validation.

**To Reproduce**
Using regexp `pattern:`^[0-9]{4}\-W[0-9]{2}$` leads to many
```
request.body.week should match pattern "^[0-9]{4}\-W[0-9]{2}$"
```
during test execution, e.g. for `0112-W03\n`, because the middleware I use, `express-openapi-validator`, seems to interpret `^` as `\A` and `$` as `\Z`.

But if I change the regexps in the OpenAPI spec to `pattern: \A[0-9]{4}\-W[0-9]{2}\Z` and let `express-openapi-validator` validate it (`validateApiSpec: true`),
its schema validation gives multipe errors of the kind:
```
  {
    "keyword": "format",
    "dataPath": ".components.schemas['Timeslot'].properties['end'].pattern",
    "schemaPath": "#/properties/pattern/format",
    "params": {
      "format": "regex"
    },
    "message": "should match format \"regex\""
  },
```

If I use `pattern: \A[0-9]{4}\-W[0-9]{2}\Z` without `express-openapi-validator` validating the spec (`validateApiSpec: false`), I still get a lot of
```
request.body.week should match pattern "\A[0-9]{4}\-W[0-9]{2}\Z"
```
during test execution because `express-openapi-validator` seems to interpret `\A` and `\Z` differently.

I need to turn off validation of requests by `express-openapi-validator` (`validateRequests: false`). But without such validation, my SUT behaves quite differently
as I use validity by `express-openapi-validator`'s validation of requests as preconditions for my functions.

**Expected behavior**
Consistent regexp interpretation or the ability to configure how regexps are intergreted.

**Environment (please complete the following information):**
 -   OS: Ubuntu
 -   Python version: 3.7.6
 -   Schemathesis version: 3.8.0
-    Spec version: 3.0.1 OpenAPI json
-    express-openapi-validator version: ^4.12.6

**Comment by Stranger6667** [comment] 2021-09-29 16:00
@DavidFarago 

Sorry for my late response. Unfortunately, this is quite complicated as we are tied to Python's regex dialect, where Open API implies the one from ECMA-262. The simplest solution would be to translate regexes from ECMA-262 to Python on the fly, but the syntax and feature differences lead to quite many subtle complications.

In the future, I'd be happy to have support for more kinds of regular expressions (e.g. Java) - #674 goes for that.

There is [a library](https://github.com/Zac-HD/js-regex) that might help, but it is unmaintained. Maybe we could consider integrating something like this.

Hi @Zac-HD , what was the reason for archiving `js-regex`? Were there any issues that may significantly limit its usability? I found https://github.com/Julian/jsonschema/issues/612 but not sure if there is something else. Thanks :)

**Comment by Zac-HD** [comment] 2021-10-02 06:44
> What was the reason for archiving `js-regex`? Were there any issues that may significantly limit its usability? I found [Julian/jsonschema#612](https://github.com/Julian/jsonschema/issues/612) but not sure if there is something else.

No, that's the "only" problem - but it's a fatal problem, which can't be solved without a proper parser for regex patterns.

The good news is that I think `greenery` would be suitable for that; one of my students implemented to- and from- Python regex syntax for it earlier this year and doing the same for js shouldn't be too hard.  That would make it easy to convert js-to-python regex, and also enable nice tricks like https://github.com/Zac-HD/hypothesis-jsonschema/issues/85/

**Comment by Zac-HD** [comment] 2021-12-15 00:17
Looking at this more closely, I think we actually can solve this *specifically for the special case of `$` by adding a reasonably small special case to Hypothesis internals, and hooking into that from `hypothesis-jsonschema`.

That means we'll cover the entire [recommended subset](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html), and while I'd still *like* to do the full syntax-conversion I'm not likely to get to that any time soon.

**Comment by Zac-HD** [comment] 2021-12-15 10:46
[`hypothesis-jsonschema >= 0.22` has a fix for this](https://pypi.org/project/hypothesis-jsonschema/); upgrade and you'll get it for free.

(I imagine @Stranger6667 will shortly issue a new Schemathesis version depending on said minimum version.)

**Comment by Stranger6667** [comment] 2021-12-15 11:07
@Zac-HD Thank you for a quick fix! Unfortunately, upgrading `hypothesis-jsonschema` will require upgrading `jsonschema` to `4.x` which has [a significant performance regression](https://github.com/Julian/jsonschema/issues/853). I didn't measure the exact effect for Schemathesis, but I am somehow hesitant to upgrade `jsonschema` until that issue is fixed :( My assumption is that that effect is partially caused by the new rules of its uniqueness check (`uniq` function works ~8x slower after upgrade).
I'll take a look at this in `jsonschema`

**Comment by Zac-HD** [comment] 2021-12-15 14:01
FWIW I'd also be happy to re-add support for jsonschema v3, if that ends up being easier; it was a fairly trivial "there are some semantic changes and it's a pain to get good test coverage of both, so just the new one then".  Maybe a day or two of work all up.

**Comment by Stranger6667** [comment] 2021-12-19 13:36
With the recent `jsonschema` release, I think that the performance regression is within an acceptable range - the library does more work with location-independent identifiers and new keywords. OP reported only ~50% slowdown compared to `3.2` vs ~430% of the original slowdown with `4.0`. So, it might be easier to upgrade `jsonschema` to `4.3.1` :)

**Closed** 2021-12-28 13:40 UTC
Labels: Type: Bug, Status: Review Needed
