### ISSUE TITLE
[BUG] HTTPConnection/HTTPSConnection is not iterable

### ISSUE THREAD

**Issue by Cokun01** [schemathesis/schemathesis#2232] opened 2024-06-03 06:50 UTC
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

When trying to run schemathesis on a bigger OAS3, I always run into the following error: 
`TypeError: argument of type 'HTTPConnection' is not iterable`.
This also happens for `HTTPSConnection`. The error mostly occurs when the tool is in the 90% - 99% of endpoint coverage, but I also saw it happen (once) earlier (at ~ 6%). The endpoint where the execution error happens is always different.

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. Run this command `schemathesis run openapi.json --checks all --base-url http://X.X.X.X:8080 --request-tls-verify=false -H "X-API-Token: [Filtered]" --show-trace`
2. See additional context

Please include a minimal API schema causing this issue:

I was only able to replicate it on the whole OAS, which is attached to the issue.

### Expected behavior

Schemathesis should complete the run and print the found bugs/conformance issues.

### Environment

```
- OS: Ubuntu 24.04 LTS (WSL2 on Windows 11 host machine)
- Python version: 3.12.3
- Schemathesis version: 3.28.1
- Spec version: Open API 3.0.0
```

### Additional context

**stack trace for HTTP:**
```
POST /rest/control/v1/service-container-control/start F                   [ 93%]
POST /rest/control/v1/service-container-control/stop Test Execution Error

An internal error occurred during the test run

    Traceback (most recent call last):
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/cli/__init__.py", line 1110, in into_event_stream
        yield from runner.from_schema(
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 194, in _generate_events
        yield from self._execute(results, stop_event)
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/solo.py", line 24, in _execute
        for event in self._execute_impl(results):
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/solo.py", line 32, in _execute_impl
        yield from self._run_tests(
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 255, in _run_tests
        for event in run_test(
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 560, in run_test
        yield events.AfterExecution.from_result(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/events.py", line 198, in from_result
        result=SerializedTestResult.from_test_result(result),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/serialization.py", line 436, in from_test_result
        errors=[SerializedError.from_exception(error) for error in result.errors],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/serialization.py", line 250, in from_exception
        message, extras = extract_requests_exception_details(exception)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/exceptions.py", line 555, in extract_requests_exception_details
        if ":" not in inner.reason.args[0]:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: argument of type 'HTTPConnection' is not iterable
```

**Stack trace for HTTPS:**
```
GET /rest/control/v1/box/system-report F                                  [ 95%]
GET /rest/control/v1/box/system-report.tgz Test Execution Error

An internal error occurred during the test run

    Traceback (most recent call last):
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/cli/__init__.py", line 1110, in into_event_stream
        yield from runner.from_schema(
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 192, in _generate_events
        yield from self._execute(results, stop_event)
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/solo.py", line 24, in _execute
        for event in self._execute_impl(results):
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/solo.py", line 32, in _execute_impl
        yield from self._run_tests(
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 253, in _run_tests
        for event in run_test(
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/impl/core.py", line 546, in run_test
        yield events.AfterExecution.from_result(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/events.py", line 198, in from_result
        result=SerializedTestResult.from_test_result(result),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/serialization.py", line 421, in from_test_result
        errors=[SerializedError.from_exception(error) for error in result.errors],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/runner/serialization.py", line 241, in from_exception
        message, extras = extract_requests_exception_details(exception)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../schemathesis/venv/lib/python3.12/site-packages/schemathesis/exceptions.py", line 547, in extract_requests_exception_details
        if ":" not in inner.reason.args[0]:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: argument of type 'HTTPSConnection' is not iterable
```
[openapi.json](https://github.com/user-attachments/files/15529843/openapi.json)

**Comment by Stranger6667** [comment] 2024-06-03 07:00
Hi! Thank you for the detailed report! The issue has been fixed in 3.29 and was reported in https://github.com/schemathesis/schemathesis/issues/2219

**Closed by Stranger6667** 2024-06-03 07:00 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by Cokun01** [comment] 2024-06-03 12:30
Hi, thanks for the fast answer and sorry for the oversight 😅.

Regarding the new release the error does indeed not occur anymore but I have a question about the output.
For endpoints where the error previously occurred (just a guess) the output now looks like this:
```
==================================== ERRORS ====================================
_____________ POST /rest/control/v1/service-container-control/stop _____________
Network Error

Connection failed

    <urllib3.connection.HTTPConnection object at 0x7fe30aeda450>
____________ POST /rest/control/v1/service-container-control/block _____________
Network Error

Connection failed

    <urllib3.connection.HTTPConnection object at 0x7fe30ad64590>
___________ POST /rest/control/v1/service-container-control/restart ____________
Network Error
```

Any plans to provide a more informative message if this occurs?
Can you tell if this happens because of a mistake with the implementation of the API or is this a caused by schemathesis?

**Comment by Stranger6667** [comment] 2024-06-03 12:43
This output is not really informative, indeed - I am keen to improve it! :)

The underlying reason is `MaxRetryError` meaning that Schemathesis made multiple attempts to send data / establish a connection and it failed. Likely it is caused by the app, but at the moment Schemathesis does not display some information that could help with debugging (i.e. the underlying exception could be Connect / Read timeout, so it could be helpful)

Let me dig a bit into this and I'll improve it in the next release

**Comment by Cokun01** [comment] 2024-06-03 13:00
Yes, I noticed shortly after the comment that a service was stopped during testing, which basically caused all connections to be blocked - so it was an API error.
