### ISSUE TITLE
[BUG] Bearer Token is not encodeable by latin-1 codec

### ISSUE THREAD

**Issue by KioLion** [schemathesis/schemathesis#1475] opened 2022-04-25 09:14 UTC
**Describe the bug**
When using Bearer Tokens for authentication, that are generated by OpenID/OAuth2 and a have length of around 1000+ characters, in some cases ( very high chance that the error occures) a `UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)` occures, while running the tests with schemathesis. Please note that the token generation happens on a seperate API, not the one being tested.

**To Reproduce**
1. Generate a Bearer Token with a length of around 1000+ characters
2. Use this token for authentication inside a schemathesis test
3. Get UnicodeEncodeError

**Expected behavior**
When providing a automatically generated Bearer Token, I expect no UnicodeEncodeError, because the Bearer Token is correct.

**Environment :**
 - OS: Windows
 - Python version: 3.10.4
 - Schemathesis version: 3.14.2
 - Spec version: OpenAPI 3.0.2

**Additional context**
The error occures when using CLI or pytest,

**Comment by Stranger6667** [comment] 2022-04-29 09:06
Hi @KioLion 

Thanks for reporting! Could you, please share such a token here + the command you ran / code you executed? 

> UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

The `\u2026` character is a Unicode version of `...` (`…` as a single char) - can it be a copy-paste artifact? Schemathesis [doesn't generate](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/specs/openapi/_hypothesis.py#L66) such characters for headers, so I'm curious how it got there. Are you using some custom formats / Hypothesis strategies? CLI validates the input headers, so I guess it should come from elsewhere, but without a code sample from your side I can't reliably solve the problem.

A stack trace (preferably a complete one) would also help, as I don't know where `UnicodeEncodeError` happens.

**Comment by KioLion** [comment] 2022-05-03 11:21
`schemathesis run -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJJdGloQUJfY1dJU09KUmJfQWRLYmc3RElDbUg4ZEg2eWxFblNkRXpQY3BFIn0.eyJleHAiOjE2NTA4NzY0NzEsImlhdCI6MTY1MDg3NTU3MSwiYXV0aF90aW1lIjoxNjUwODc1NTcxLCJqdGkiOiJiMjg3YWJmNy0yZTNlLTQzMjQtODQwMi05ODY0YWE0OTE0ZDEiLCJpc3MiOiJodHRwczovL2lkZW50aXR5LnBsYXR0Zm9ybS5pcG9sb2cuYWkvYXV0aC9yZWFsbXMvaXBvbG9nIiwic3ViIjoiYzZhNmJmNmItM2RkZS00NmNkLTk0MDAtMWY4Nzk5ZjdkYzdjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaXBvbG9nIiwic2Vzc2lvbl9zdGF0ZSI6IjZlMjA5NGIwLTg3NTctNDJiMy1iNjRkLWE2ZjVjMTNhOGM3Z.QnJ1ZyIsInByZWZlcnJlZF91c2VybmFtZSI6ImRhbmllbC5icnVnQGlwb2xvZy5haSIsImdpdmVuX25hbWUiOiJEYW5pZWwiLCJmYW1pbHlfbmFtZSI6IkJydWciLCJlbWFpbCI6ImRhbmllbC5icnVnQGlwb2xvZy5haSJ9.Md62POcXHjnul_2nEApRPausjUwdCeoVnqf4TNcZLDGwPqyRJ2uyr-bIb7TokcASJnAnqI2WW9WLm0nDOO_82KTJ05fHmvrwKVJ7us47TKTpUAdG1NLLI52JjhYorZ1L9_wUtkPeRgQ7UUE0j_Zajo37tH2srOsvzGCxZF2FaOHwGHO95JMiHOXoK1MnIWDHWslrhgozTL43wHpIx45d1ddP7tDTpv0OwllTHa0MqWN3l2r11kYysKCovQB7jgcsGF5ArN_-mLkSmqbkESI2ejF9XDYTrjgFDcMJ02NvKNemUkCGHQbcDUXEdpodGsnclQFDGg-Lt7PcNNdbgsHkng" --checks=all http://localhost:8002/openapi.json  `

Hi @Stranger6667,

thank you for answering.  I provided a CLI command that was raising the described issue.
I also already noticed the ellipses should not be part of the token and I really dont have an idea, where it's coming from. 
I dont think it's a artifact from copy and paste, as I was formatting the token to fit into one line.

I will try to provide a stacktrace as soon as possible, but for now the CLI command was easy to find and I'm currently on an other topic.

Thanks a lot! I really like the framework so far and I hope my team can use it for our product soon :)

**Comment by Stranger6667** [comment] 2022-05-03 13:50
You're very welcome :) The command above works fine on my machine when I run it against `https://example.schemathesis.io/openapi.json`, but the API is different and might not expose the actual issue :( 

> Thanks a lot! I really like the framework so far and I hope my team can use it for our product soon :)

Great to hear it :) Feel free to reach out to me if you need any support

**Comment by Stranger6667** [comment] 2022-06-11 10:57
Hi @KioLion ! I am going to close the issue for now. But feel free to reopen it if the issue persists. At this point I am inclined to think that the issue is outside of Schemathesis itself.

**Closed by Stranger6667** 2022-06-11 10:57 UTC
Labels: Type: Bug, Status: Review Needed
