### ISSUE TITLE
[BUG] KeyError when loading schema from pytest fixrture

### ISSUE THREAD

**Issue by kwmlodozeniec** [schemathesis/schemathesis#1451] opened 2022-04-13 16:23 UTC
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
When I try to load the schema from a pytest fixture I get a long traceback error with KeyError matching one of the paths in the API. Loading the same schema directly from FastAPI app instance works fine.

```
platform linux -- Python 3.8.6, pytest-7.1.0, pluggy-1.0.0
rootdir: /home/krzysztof/repos/service, configfile: pyproject.toml, testpaths: tests
plugins: hypothesis-6.43.1, schemathesis-3.13.8, subtests-0.7.0, typeguard-2.13.3, cov-3.0.0, mock-3.7.0, anyio-3.5.0, depends-1.0.1
collected 33 items / 32 deselected / 1 selected

tests/framework/test_unauthorised.py::test_auth_forbidden
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/_pytest/main.py", line 347, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/_pytest/runner.py", line 111, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/_pytest/runner.py", line 130, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/_pytest/runner.py", line 221, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pytest_depends/__init__.py", line 139, in pytest_runtest_makereport
INTERNALERROR>     manager.register_result(item, outcome.get_result())
INTERNALERROR>   File "/home/krzysztof/.pyenv/versions/3.8.6/envs/service/lib/python3.8/site-packages/pytest_depends/main.py", line 209, in register_result
INTERNALERROR>     self.results[nodeid].register_result(result)
INTERNALERROR> KeyError: 'tests/framework/test_unauthorised.py::test_auth_forbidden[GET /healthz][P]'
```

Pytest fixture

```
@pytest.fixture()
def api_schema(service_url) -> BaseOpenAPISchema:
    return schemathesis.from_dict(app.openapi(), base_url=f"{service_url}")
```

I am not sure if this can be reproduced, I only tried it with a single service.

**Expected behavior**
Schema should be loaded without issues.

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Python version: 3.8.6
 - Schemathesis version: 3.13.8
 - Spec version: Open API 3.0.2

**Comment by Stranger6667** [comment] 2022-04-14 09:22
Hi @kwmlodozeniec 

Thanks for reporting! This is a tricky one :( Schemathesis uses a custom collector to generate tests, and I did not yet dig deep enough to understand why those "expanded" collected items aren't going to the `pytest_collection_modifyitems` [here](https://gitlab.com/MaienM/pytest-depends/-/blob/master/src/pytest_depends/__init__.py#L117). I'd assume that disabling the `pytest-depends` plugin should fix the issue with Schemathesis + running those tests separately might be acceptable, but it is not a proper solution :( The problem is legit to me, but I need more time to investigate the cause

**Comment by kwmlodozeniec** [comment] 2022-04-14 10:17
@Stranger6667 thanks for a quick response. I have realised I no longer need the depends plugin so I removed it and the call now works fine.

**Comment by Stranger6667** [comment] 2022-04-14 10:34
Great! I'll keep the issue open, so we can improve interoperability with this and other plugins in the future

**Comment by Stranger6667** [comment] 2023-10-18 20:19
Looks like `pytest-depends` is abandoned. The issue seems to happen due to `pytest-depends` not accounting for tests generated via `pytest_generate_tests` & others. Hence I am going to close the issue

**Closed by Stranger6667** 2023-10-18 20:19 UTC
Labels: Type: Bug, Difficulty: Intermediate, UX: Reporting
